# Generated by Django 5.0.6 on 2024-07-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="simbolo",
            field=models.FileField(upload_to=""),
        ),
    ]
