# Generated by Django 5.0.6 on 2024-07-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_categoria_simbolo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="simbolo",
        ),
    ]
