# Generated by Django 5.0.6 on 2024-07-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_categoria_simbolo"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="simbolo",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
