# Generated by Django 5.0.6 on 2024-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_user_genero_alter_categoria_simbolo_trabalho_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trabalho",
            old_name="data",
            new_name="dataInicio",
        ),
        migrations.AlterField(
            model_name="trabalho",
            name="DataTermino",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trabalho",
            name="preco",
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
