# Generated by Django 5.0.6 on 2024-08-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_data_trabalho_datainicio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorito",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pagfavorito", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="trabalho",
            name="pagfavorito",
            field=models.ManyToManyField(blank=True, null=True, related_name="paginasfavoritos", to="core.favorito"),
        ),
    ]
