# Generated by Django 5.0.6 on 2024-08-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_delete_favorito_alter_trabalho_pagfavorito"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trabalho",
            name="pagfavorito",
        ),
    ]
