# Generated by Django 5.0.6 on 2024-08-13 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_trabalho_pagfavorito"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trabalho",
            name="usuario",
        ),
        migrations.AddField(
            model_name="user",
            name="favorito",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
