# Generated by Django 5.0.6 on 2024-08-13 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_trabalho_usuario_user_favorito"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favorito",
        ),
        migrations.AddField(
            model_name="user",
            name="favorito",
            field=models.ManyToManyField(
                related_name="favoritos", related_query_name="fas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
