# Generated by Django 5.0.6 on 2024-08-14 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_avaliacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabalho",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente",
                related_query_name="trabalhadores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
