# Generated by Django 5.0.6 on 2024-08-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_trabalho_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trabalho",
            old_name="name",
            new_name="nome",
        ),
    ]
