# Generated by Django 5.0.6 on 2024-08-16 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_rename_name_trabalho_nome"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trabalho",
            old_name="dataInicio",
            new_name="DataInicio",
        ),
        migrations.AlterField(
            model_name="trabalho",
            name="nome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cliente",
                related_query_name="trabalhadores",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
