# Generated by Django 5.0.6 on 2024-09-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_user_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tipo",
            field=models.IntegerField(choices=[(1, "Cliente"), (2, "Trabalhador"), (3, "Admin")], default=3),
        ),
    ]
