# Generated by Django 5.0.6 on 2024-09-27 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_trabalho_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabalho",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Categoria",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trabalho",
            name="estado",
            field=models.IntegerField(
                choices=[(1, "Negocio"), (2, "Em andamento"), (3, "Concluido"), (4, "Pago"), (5, "Cancelado")],
                default=1,
            ),
        ),
    ]
