# Generated by Django 5.0.6 on 2024-09-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_trabalho_categoria_alter_trabalho_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trabalho",
            name="categoria",
        ),
    ]
