# Generated by Django 5.0.6 on 2024-10-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_remove_trabalho_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabalho",
            name="clienteAvaliacao",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trabalho",
            name="trabalhadorAvaliacao",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Avaliacao",
        ),
    ]
