# Generated by Django 5.0.6 on 2024-10-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_user_capa_user_publicacao_user_publicacaofoto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favorito",
        ),
    ]
